import { AbpHttpInterceptor, RefreshTokenService, AbpHttpConfigurationService } from 'abp-ng2-module';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import * as ApiServiceProxies from './service-proxies';
import { ZeroRefreshTokenService } from '@account/auth/zero-refresh-token.service';
import { ZeroTemplateHttpConfigurationService } from './zero-template-http-configuration.service';

@NgModule({
    providers: [
        ApiServiceProxies.AuditLogServiceProxy,
        ApiServiceProxies.CachingServiceProxy,
        ApiServiceProxies.ChatServiceProxy,
        ApiServiceProxies.CommonLookupServiceProxy,
        ApiServiceProxies.EditionServiceProxy,
        ApiServiceProxies.FriendshipServiceProxy,
        ApiServiceProxies.HostSettingsServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.LanguageServiceProxy,
        ApiServiceProxies.NotificationServiceProxy,
        ApiServiceProxies.OrganizationUnitServiceProxy,
        ApiServiceProxies.PermissionServiceProxy,
        ApiServiceProxies.ProfileServiceProxy,
        ApiServiceProxies.RoleServiceProxy,
        ApiServiceProxies.SessionServiceProxy,
        ApiServiceProxies.TenantServiceProxy,
        ApiServiceProxies.TenantDashboardServiceProxy,
        ApiServiceProxies.TenantSettingsServiceProxy,
        ApiServiceProxies.TimingServiceProxy,
        ApiServiceProxies.UserServiceProxy,
        ApiServiceProxies.UserLinkServiceProxy,
        ApiServiceProxies.UserLoginServiceProxy,
        ApiServiceProxies.WebLogServiceProxy,
        ApiServiceProxies.AccountServiceProxy,
        ApiServiceProxies.TokenAuthServiceProxy,
        ApiServiceProxies.TenantRegistrationServiceProxy,
        ApiServiceProxies.HostDashboardServiceProxy,
        ApiServiceProxies.PaymentServiceProxy,
        ApiServiceProxies.DemoUiComponentsServiceProxy,
        ApiServiceProxies.InvoiceServiceProxy,
        ApiServiceProxies.SubscriptionServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.UiCustomizationSettingsServiceProxy,
        ApiServiceProxies.PayPalPaymentServiceProxy,
        ApiServiceProxies.StripePaymentServiceProxy,
        ApiServiceProxies.DashboardCustomizationServiceProxy,
        ApiServiceProxies.WebhookEventServiceProxy,
        ApiServiceProxies.WebhookSubscriptionServiceProxy,
        ApiServiceProxies.WebhookSendAttemptServiceProxy,
        ApiServiceProxies.UserDelegationServiceProxy,
        ApiServiceProxies.DynamicPropertyServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyDefinitionServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyServiceProxy,
        ApiServiceProxies.DynamicPropertyValueServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyValueServiceProxy,
        ApiServiceProxies.TwitterServiceProxy,
        ApiServiceProxies.MessagingServiceServiceProxy,

        //New Proxies
        ApiServiceProxies.DocumentServiceProxy,
        ApiServiceProxies.RequisitionServiceServiceProxy,
        ApiServiceProxies.NonFixedAssetAllocationServicesServiceProxy,
        ApiServiceProxies.AccrualServiceServiceProxy,
        ApiServiceProxies.BudgetManagerServiceServiceProxy,
        ApiServiceProxies.ProcurementQuoteServiceServiceProxy,
        ApiServiceProxies.PurchaseRequisitionServiceServiceProxy,
        ApiServiceProxies.VendorQuoteServiceServiceProxy,
        ApiServiceProxies.GeneralOperationsServiceServiceProxy,
        ApiServiceProxies.StaffCategoryServiceServiceProxy,
        ApiServiceProxies.SharingGroupServiceServiceProxy,
        ApiServiceProxies.NormalTaxServiceServiceProxy,
        ApiServiceProxies.DefaultAccountDetailsServiceServiceProxy,
        ApiServiceProxies.WorkflowServiceServiceProxy,
        ApiServiceProxies.OperatingExpenseServiceServiceProxy,
        ApiServiceProxies.FinanceOperationServiceServiceProxy,
        ApiServiceProxies.FinanceReportServiceServiceProxy,
        ApiServiceProxies.ChartofAccountServiceServiceProxy,
        ApiServiceProxies.BankRecSetUpClassCodeServiceServiceProxy,
        ApiServiceProxies.BankReconciliationServiceServiceProxy,
        ApiServiceProxies.BankReconciliationMatchingServicesServiceProxy,
        ApiServiceProxies.AccountBankMappingServiceServiceProxy,
        ApiServiceProxies.BankReconciliationReportServiceServiceProxy,
        ApiServiceProxies.ProcessPayrollServiceServiceProxy,
        ApiServiceProxies.PayPolicyServiceServiceProxy,
        ApiServiceProxies.PayCodeDefinitionServiceServiceProxy,
        ApiServiceProxies.SharingRateServiceServiceProxy,
        ApiServiceProxies.EmployeeServiceServiceProxy,
        ApiServiceProxies.BranchServiceServiceProxy,
        ApiServiceProxies.CompanySubsidiaryServiceServiceProxy,
        ApiServiceProxies.HMOServiceServiceProxy,
        ApiServiceProxies.UnitServiceServiceProxy,
        ApiServiceProxies.DesignationServiceServiceProxy,
        ApiServiceProxies.DepartmentServiceServiceProxy,
        ApiServiceProxies.WFormServiceServiceProxy,
        ApiServiceProxies.CashAdvanceServiceServiceProxy,
        ApiServiceProxies.CompanyStructureServiceProxy,
        


        { provide: RefreshTokenService, useClass: ZeroRefreshTokenService },
        { provide: AbpHttpConfigurationService, useClass: ZeroTemplateHttpConfigurationService },
        { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true }
    ]
})
export class ServiceProxyModule { }
